### ISSUE TITLE
Dosent work

### ISSUE THREAD

**Issue by ichbinder** [jalada/Paw-HawkDynamicValue#6]
<img width="716" alt="bildschirmfoto 2018-12-26 um 06 25 00" src="https://user-images.githubusercontent.com/1057588/50433247-44fe0600-08d7-11e9-8afe-c223d2b4d588.png">

I can not chose Hawk Auth.

**Comment by jalada** [comment]
It's a dynamic value, not an auth scheme (I don't think that was a feature when I made this for Paw). So you use it under Headers instead like this:

<img width="576" alt="screenshot 2019-01-01 at 16 50 58" src="https://user-images.githubusercontent.com/126989/50574688-6f732600-0de5-11e9-9127-9c0a7e879ffc.png">
